# Generated by Django 6.0.5 on 2026-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="auth_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("code_verify", "code_verify"),
                    ("change_info", "change_info"),
                    ("upload_avatar_done", "upload_avatar_done"),
                    ("done", "done"),
                ],
                default="new",
                max_length=250,
            ),
        ),
    ]
