# Generated by Django 6.0.5 on 2026-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_review_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Naqd pul"), ("card", "Plastik karta")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
